// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PBMS.Registry.API.Persistence;

#nullable disable

namespace PBMS.Registry.API.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    [Migration("20260605044726_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PBMS.Registry.API.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowedVehicleTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllowedVehicleTypeId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("PBMS.Registry.API.Models.ParkingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DistanceMetric")
                        .HasColumnType("integer");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SlotNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId", "Status")
                        .HasDatabaseName("IX_ParkingSlots_FloorId_Status");

                    b.ToTable("ParkingSlots");
                });

            modelBuilder.Entity("PBMS.Registry.API.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two-wheeled motor vehicle",
                            Name = "Motorbike"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Four-wheeled passenger car",
                            Name = "Compact Car"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sport Utility Vehicle / Large car",
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Electric Vehicle",
                            Name = "EV"
                        });
                });

            modelBuilder.Entity("PBMS.Registry.API.Models.Floor", b =>
                {
                    b.HasOne("PBMS.Registry.API.Models.VehicleType", "AllowedVehicleType")
                        .WithMany()
                        .HasForeignKey("AllowedVehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllowedVehicleType");
                });

            modelBuilder.Entity("PBMS.Registry.API.Models.ParkingSlot", b =>
                {
                    b.HasOne("PBMS.Registry.API.Models.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });
#pragma warning restore 612, 618
        }
    }
}
