CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "VehicleTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(200),
    CONSTRAINT "PK_VehicleTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Floors" (
    "Id" uuid NOT NULL,
    "FloorNumber" integer NOT NULL,
    "AllowedVehicleTypeId" integer NOT NULL,
    "TotalSlots" integer NOT NULL,
    CONSTRAINT "PK_Floors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Floors_VehicleTypes_AllowedVehicleTypeId" FOREIGN KEY ("AllowedVehicleTypeId") REFERENCES "VehicleTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ParkingSlots" (
    "Id" uuid NOT NULL,
    "FloorId" uuid NOT NULL,
    "SlotNumber" character varying(20) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "DistanceMetric" integer NOT NULL,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_ParkingSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ParkingSlots_Floors_FloorId" FOREIGN KEY ("FloorId") REFERENCES "Floors" ("Id") ON DELETE CASCADE
);

INSERT INTO "VehicleTypes" ("Id", "Description", "Name")
VALUES (1, 'Two-wheeled motor vehicle', 'Motorbike');
INSERT INTO "VehicleTypes" ("Id", "Description", "Name")
VALUES (2, 'Four-wheeled passenger car', 'Compact Car');
INSERT INTO "VehicleTypes" ("Id", "Description", "Name")
VALUES (3, 'Sport Utility Vehicle / Large car', 'SUV');
INSERT INTO "VehicleTypes" ("Id", "Description", "Name")
VALUES (4, 'Electric Vehicle', 'EV');

CREATE INDEX "IX_Floors_AllowedVehicleTypeId" ON "Floors" ("AllowedVehicleTypeId");

CREATE INDEX "IX_ParkingSlots_FloorId_Status" ON "ParkingSlots" ("FloorId", "Status");

SELECT setval(
    pg_get_serial_sequence('"VehicleTypes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "VehicleTypes") + 1,
        nextval(pg_get_serial_sequence('"VehicleTypes"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260605044726_InitialCreate', '8.0.8');

COMMIT;

