CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ParkingSessions" (
    "Id" uuid NOT NULL,
    "CardNumber" character varying(50) NOT NULL,
    "LicensePlate" character varying(20) NOT NULL,
    "VehicleTypeId" integer NOT NULL,
    "AllocatedSlotId" uuid,
    "CheckInTime" timestamp with time zone NOT NULL,
    "CheckOutTime" timestamp with time zone,
    "TotalFee" numeric(18,2),
    "Status" character varying(20) NOT NULL,
    CONSTRAINT "PK_ParkingSessions" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_ParkingSessions_CardNumber_Status" ON "ParkingSessions" ("CardNumber", "Status");

CREATE INDEX "IX_ParkingSessions_LicensePlate_Status" ON "ParkingSessions" ("LicensePlate", "Status");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260605044731_InitialCreate', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE "InboxState" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" uuid NOT NULL,
    "ConsumerId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Received" timestamp with time zone NOT NULL,
    "ReceiveCount" integer NOT NULL,
    "ExpirationTime" timestamp with time zone,
    "Consumed" timestamp with time zone,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
);

CREATE TABLE "OutboxMessage" (
    "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EnqueueTime" timestamp with time zone,
    "SentTime" timestamp with time zone NOT NULL,
    "Headers" text,
    "Properties" text,
    "InboxMessageId" uuid,
    "InboxConsumerId" uuid,
    "OutboxId" uuid,
    "MessageId" uuid NOT NULL,
    "ContentType" character varying(256) NOT NULL,
    "MessageType" text NOT NULL,
    "Body" text NOT NULL,
    "ConversationId" uuid,
    "CorrelationId" uuid,
    "InitiatorId" uuid,
    "RequestId" uuid,
    "SourceAddress" character varying(256),
    "DestinationAddress" character varying(256),
    "ResponseAddress" character varying(256),
    "FaultAddress" character varying(256),
    "ExpirationTime" timestamp with time zone,
    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber")
);

CREATE TABLE "OutboxState" (
    "OutboxId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Created" timestamp with time zone NOT NULL,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
);

CREATE INDEX "IX_InboxState_Delivered" ON "InboxState" ("Delivered");

CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");

CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");

CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");

CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON "OutboxMessage" ("OutboxId", "SequenceNumber");

CREATE INDEX "IX_OutboxState_Created" ON "OutboxState" ("Created");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260605060202_AddMassTransitOutbox', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "ParkingSessions" RENAME COLUMN "Id" TO "CorrelationId";

ALTER TABLE "ParkingSessions" ADD "CurrentState" character varying(64) NOT NULL DEFAULT '';

ALTER TABLE "ParkingSessions" ADD "Version" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260605062512_AddParkingSessionSaga', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE INDEX "IX_ParkingSessions_CardNumber_LicensePlate_Status_CheckInTime" ON "ParkingSessions" ("CardNumber", "LicensePlate", "Status", "CheckInTime");

CREATE INDEX "IX_ParkingSessions_CheckInTime" ON "ParkingSessions" ("CheckInTime");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260605064832_AddPerformanceIndexes', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "ParkingSessions" ADD "Notes" character varying(500);

CREATE TABLE "Bookings" (
    "Id" uuid NOT NULL,
    "LicensePlate" character varying(20) NOT NULL,
    "VehicleTypeId" integer NOT NULL,
    "SlotId" uuid NOT NULL,
    "SlotNumber" character varying(20) NOT NULL,
    "BookingTimeUtc" timestamp with time zone NOT NULL,
    "ExpiryTimeUtc" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id")
);

CREATE TABLE "PricingRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleTypeId" integer NOT NULL,
    "RatePerHour" numeric(18,2) NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PricingRules" PRIMARY KEY ("Id")
);

INSERT INTO "PricingRules" ("Id", "RatePerHour", "UpdatedAtUtc", "VehicleTypeId")
VALUES (1, 5000.0, NOW(), 1);
INSERT INTO "PricingRules" ("Id", "RatePerHour", "UpdatedAtUtc", "VehicleTypeId")
VALUES (2, 20000.0, NOW(), 2);
INSERT INTO "PricingRules" ("Id", "RatePerHour", "UpdatedAtUtc", "VehicleTypeId")
VALUES (3, 30000.0, NOW(), 3);
INSERT INTO "PricingRules" ("Id", "RatePerHour", "UpdatedAtUtc", "VehicleTypeId")
VALUES (4, 15000.0, NOW(), 4);

CREATE INDEX "IX_Bookings_LicensePlate_Status" ON "Bookings" ("LicensePlate", "Status");

CREATE UNIQUE INDEX "IX_PricingRules_VehicleTypeId" ON "PricingRules" ("VehicleTypeId");

SELECT setval(
    pg_get_serial_sequence('"PricingRules"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "PricingRules") + 1,
        nextval(pg_get_serial_sequence('"PricingRules"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260610082425_AddPricingAndBookings', '8.0.8');

COMMIT;
